// Built-in symbol lists. These fill the textarea; you can edit them freely.
// NOTE: Index constituents change over time — verify against NSE before relying on them.
// The loader pages any list into chunks of 30, so just paste the whole universe.

window.PRESETS = {
  // Top 30 Nifty stocks by weight (user-curated). Exactly one page of 30.
  "Nifty Top 30": [
    "NSE:RELIANCE", "NSE:HDFCBANK", "NSE:BHARTIARTL", "NSE:TCS", "NSE:BAJFINANCE",
    "NSE:LT", "NSE:HINDUNILVR", "NSE:SBIN", "NSE:SUNPHARMA", "NSE:ADANIPORTS",
    "NSE:MARUTI", "NSE:ADANIENT", "NSE:KOTAKBANK", "NSE:TITAN", "NSE:M_M",
    "NSE:NTPC", "NSE:ITC", "NSE:ONGC", "NSE:BAJAJFINSV", "NSE:POWERGRID",
    "NSE:TATASTEEL", "NSE:TATAMOTORS", "NSE:ULTRACEMCO", "NSE:ASIANPAINT", "NSE:TRENT",
    "NSE:JSWSTEEL", "NSE:COALINDIA", "NSE:BEL", "NSE:CIPLA", "NSE:DRREDDY"
  ],

  // Nifty 50 (NSE). ~50 names — the loader will split this into 2 pages of 30.
  "Nifty 50": [
    "NSE:ADANIENT", "NSE:ADANIPORTS", "NSE:APOLLOHOSP", "NSE:ASIANPAINT", "NSE:AXISBANK",
    "NSE:BAJAJ_AUTO", "NSE:BAJFINANCE", "NSE:BAJAJFINSV", "NSE:BEL", "NSE:BHARTIARTL",
    "NSE:CIPLA", "NSE:COALINDIA", "NSE:DRREDDY", "NSE:EICHERMOT", "NSE:ETERNAL",
    "NSE:GRASIM", "NSE:HCLTECH", "NSE:HDFCBANK", "NSE:HDFCLIFE", "NSE:HEROMOTOCO",
    "NSE:HINDALCO", "NSE:HINDUNILVR", "NSE:ICICIBANK", "NSE:INDUSINDBK", "NSE:INFY",
    "NSE:ITC", "NSE:JIOFIN", "NSE:JSWSTEEL", "NSE:KOTAKBANK", "NSE:LT",
    "NSE:M_M", "NSE:MARUTI", "NSE:NESTLEIND", "NSE:NTPC", "NSE:ONGC",
    "NSE:POWERGRID", "NSE:RELIANCE", "NSE:SBILIFE", "NSE:SBIN", "NSE:SHRIRAMFIN",
    "NSE:SUNPHARMA", "NSE:TATACONSUM", "NSE:TATAMOTORS", "NSE:TATASTEEL", "NSE:TCS",
    "NSE:TECHM", "NSE:TITAN", "NSE:TRENT", "NSE:ULTRACEMCO", "NSE:WIPRO"
  ],

  // Nifty Next 50 (NSE). Best-effort list — verify and edit as needed.
  "Nifty Next 50": [
    "NSE:ABB", "NSE:ADANIENSOL", "NSE:ADANIGREEN", "NSE:ADANIPOWER", "NSE:AMBUJACEM",
    "NSE:BAJAJHLDNG", "NSE:BANKBARODA", "NSE:BPCL", "NSE:BRITANNIA", "NSE:CGPOWER",
    "NSE:CHOLAFIN", "NSE:DABUR", "NSE:DIVISLAB", "NSE:DLF", "NSE:DMART",
    "NSE:GAIL", "NSE:GODREJCP", "NSE:HAL", "NSE:HAVELLS", "NSE:HYUNDAI",
    "NSE:ICICIGI", "NSE:ICICIPRULI", "NSE:INDHOTEL", "NSE:INDIGO", "NSE:IOC",
    "NSE:IRFC", "NSE:JINDALSTEL", "NSE:JSWENERGY", "NSE:LICI", "NSE:LODHA",
    "NSE:LTIM", "NSE:MOTHERSON", "NSE:NAUKRI", "NSE:PFC", "NSE:PIDILITIND",
    "NSE:PNB", "NSE:RECLTD", "NSE:SBICARD", "NSE:SIEMENS", "NSE:SWIGGY",
    "NSE:TATAPOWER", "NSE:TORNTPHARM", "NSE:TVSMOTOR", "NSE:UNITDSPR", "NSE:VBL",
    "NSE:VEDL", "NSE:ZYDUSLIFE", "NSE:CANBK", "NSE:GICRE", "NSE:NHPC"
  ]
};
